# Generated by Django 5.1.6 on 2025-02-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20250215_2344"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_medical",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
